using System;
using System.Net;
using System.Text;

namespace WindowsNetTool.Tools.Export
{
	public enum ExportFormat
	{
		Text,
		Html,
		Csv
	}

	/// <summary>
	/// Renders <see cref="ExportableContent"/> as plain text, as a standalone HTML document, or as
	/// CSV.  Each rendering is a pure function of the content, so the same string can be written to
	/// a file or placed on the clipboard.
	/// </summary>
	public static class Exporter
	{
		public static string Render(ExportableContent content, ExportFormat format)
		{
			switch (format)
			{
				case ExportFormat.Html: return RenderHtml(content);
				case ExportFormat.Csv: return RenderCsv(content);
				default: return RenderText(content);
			}
		}

		/// <summary>The conventional file extension for the format, with the leading dot.</summary>
		public static string FileExtension(ExportFormat format)
		{
			switch (format)
			{
				case ExportFormat.Html: return ".html";
				case ExportFormat.Csv: return ".csv";
				default: return ".txt";
			}
		}

		#region Plain text

		private static string RenderText(ExportableContent content)
		{
			StringBuilder sb = new StringBuilder();
			sb.AppendLine(content.Title);
			sb.AppendLine("Generated by WindowsNetTool on " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));
			foreach (ExportSection section in content.Sections)
			{
				sb.AppendLine();
				if (!string.IsNullOrEmpty(section.Heading))
					sb.AppendLine("=== " + section.Heading + " ===");
				if (section.IsTable)
					AppendTextTable(sb, section);
				else
					sb.AppendLine(section.Text.TrimEnd('\r', '\n'));
			}
			return sb.ToString();
		}

		/// <summary>Renders a table as space-padded columns under a dashed header rule.</summary>
		private static void AppendTextTable(StringBuilder sb, ExportSection section)
		{
			int[] widths = new int[section.Columns.Length];
			for (int i = 0; i < section.Columns.Length; i++)
				widths[i] = section.Columns[i].Length;
			foreach (string[] row in section.Rows)
				for (int i = 0; i < widths.Length && i < row.Length; i++)
					if (row[i] != null && row[i].Length > widths[i])
						widths[i] = row[i].Length;

			string[] rules = new string[widths.Length];
			for (int i = 0; i < widths.Length; i++)
				rules[i] = new string('-', widths[i]);

			AppendTextRow(sb, section.Columns, widths);
			AppendTextRow(sb, rules, widths);
			foreach (string[] row in section.Rows)
				AppendTextRow(sb, row, widths);
			if (section.Rows.Count == 0)
				sb.AppendLine("(no entries)");
		}

		private static void AppendTextRow(StringBuilder sb, string[] cells, int[] widths)
		{
			StringBuilder line = new StringBuilder();
			for (int i = 0; i < widths.Length; i++)
			{
				string cell = i < cells.Length && cells[i] != null ? cells[i] : "";
				line.Append(i + 1 < widths.Length ? cell.PadRight(widths[i] + 2) : cell);
			}
			sb.AppendLine(line.ToString().TrimEnd());
		}

		#endregion

		#region HTML

		private static string RenderHtml(ExportableContent content)
		{
			// The fragment markers make the same document directly usable as a CF_HTML clipboard
			// payload; in a saved file they are just harmless comments.
			StringBuilder body = new StringBuilder();
			body.AppendLine("<!--StartFragment-->");
			body.AppendLine("<h1>" + Encode(content.Title) + "</h1>");
			body.AppendLine("<p class=\"meta\">Generated by WindowsNetTool on " + Encode(DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss")) + "</p>");
			foreach (ExportSection section in content.Sections)
			{
				if (!string.IsNullOrEmpty(section.Heading))
					body.AppendLine("<h2>" + Encode(section.Heading) + "</h2>");
				if (section.IsTable)
					AppendHtmlTable(body, section);
				else
					body.AppendLine("<pre>" + Encode(section.Text.TrimEnd('\r', '\n')) + "</pre>");
			}
			body.AppendLine("<!--EndFragment-->");

			StringBuilder sb = new StringBuilder();
			sb.AppendLine("<!DOCTYPE html>");
			sb.AppendLine("<html>");
			sb.AppendLine("<head>");
			sb.AppendLine("<meta charset=\"utf-8\">");
			sb.AppendLine("<title>" + Encode(content.Title) + "</title>");
			sb.AppendLine("<style>");
			sb.AppendLine("body { font-family: 'Segoe UI', Arial, sans-serif; font-size: 13px; color: #1a1a1a; margin: 24px; }");
			sb.AppendLine("h1 { font-size: 20px; margin: 0 0 4px 0; }");
			sb.AppendLine("h2 { font-size: 15px; margin: 18px 0 6px 0; }");
			sb.AppendLine(".meta { color: #666666; margin: 0 0 12px 0; }");
			sb.AppendLine("table { border-collapse: collapse; margin: 6px 0 12px 0; }");
			sb.AppendLine("th, td { border: 1px solid #bbbbbb; padding: 3px 9px; text-align: left; }");
			sb.AppendLine("th { background: #eeeeee; }");
			sb.AppendLine("pre { font-family: Consolas, monospace; font-size: 12px; margin: 6px 0 12px 0; }");
			sb.AppendLine("</style>");
			sb.AppendLine("</head>");
			sb.AppendLine("<body>");
			sb.Append(body);
			sb.AppendLine("</body>");
			sb.AppendLine("</html>");
			return sb.ToString();
		}

		private static void AppendHtmlTable(StringBuilder sb, ExportSection section)
		{
			sb.AppendLine("<table>");
			sb.Append("<thead><tr>");
			foreach (string column in section.Columns)
				sb.Append("<th>" + Encode(column) + "</th>");
			sb.AppendLine("</tr></thead>");
			sb.AppendLine("<tbody>");
			foreach (string[] row in section.Rows)
			{
				sb.Append("<tr>");
				for (int i = 0; i < section.Columns.Length; i++)
					sb.Append("<td>" + Encode(i < row.Length && row[i] != null ? row[i] : "") + "</td>");
				sb.AppendLine("</tr>");
			}
			sb.AppendLine("</tbody>");
			sb.AppendLine("</table>");
			if (section.Rows.Count == 0)
				sb.AppendLine("<p>(no entries)</p>");
		}

		private static string Encode(string text)
		{
			return WebUtility.HtmlEncode(text);
		}

		#endregion

		#region CSV

		private static string RenderCsv(ExportableContent content)
		{
			// A lone unnamed table (the common case) exports as a clean spreadsheet with no title
			// rows.  Multi-section content separates the sections with blank rows, each section's
			// heading as a one-cell row and text as one cell per line.
			StringBuilder sb = new StringBuilder();
			bool first = true;
			foreach (ExportSection section in content.Sections)
			{
				if (!first)
					sb.AppendLine();
				first = false;
				if (!string.IsNullOrEmpty(section.Heading))
					sb.AppendLine(CsvField(section.Heading));
				if (section.IsTable)
					AppendCsvTable(sb, section);
				else
					foreach (string line in section.Text.TrimEnd('\r', '\n').Replace("\r\n", "\n").Split('\n'))
						sb.AppendLine(CsvField(line));
			}
			return sb.ToString();
		}

		private static void AppendCsvTable(StringBuilder sb, ExportSection section)
		{
			AppendCsvRow(sb, section.Columns, section.Columns.Length);
			foreach (string[] row in section.Rows)
				AppendCsvRow(sb, row, section.Columns.Length);
		}

		private static void AppendCsvRow(StringBuilder sb, string[] cells, int count)
		{
			for (int i = 0; i < count; i++)
			{
				if (i > 0)
					sb.Append(',');
				sb.Append(CsvField(i < cells.Length ? cells[i] : ""));
			}
			sb.AppendLine();
		}

		private static string CsvField(string value)
		{
			if (value == null)
				return "";
			bool quote = value.IndexOfAny(new char[] { ',', '"', '\r', '\n' }) >= 0
				|| value.StartsWith(" ") || value.EndsWith(" ");
			return quote ? "\"" + value.Replace("\"", "\"\"") + "\"" : value;
		}

		#endregion
	}
}
